#!/usr/bin/env node

const fs = require('fs');
const cleaner = require('./ut99-map-cleaner-lib.js');

const inputFilename = process.argv[2];
const outputFilename = process.argv[3];

const inputText = fs.readFileSync(inputFilename, 'utf-8');

const outputText = cleaner.alignToGrid(inputText, { resolution: 0.1 });

fs.writeFileSync(outputFilename, outputText);
