#!/usr/bin/env bash
":" //# comment; exec /usr/bin/env node --input-type=module - "$@" < "$0"

import fs from 'fs';
import { cleaner } from './ut99-map-cleaner-lib.mjs'

const inputFilename = process.argv[2];
const outputFilename = process.argv[3];

const inputText = fs.readFileSync(inputFilename, 'utf-8');

const outputText = cleaner.alignToGrid(inputText, { resolution: 0.1 });

fs.writeFileSync(outputFilename, outputText);
